spring.application.name=agencia-viagens-api
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agencia_viagens
spring.datasource.username=postgres
spring.datasource.password=Senai123

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false
